name: Sync Sellbrite Inventory

on:
  schedule:
    - cron: "0 3 * * *" # 3AM UTC == 9PM CST
  workflow_dispatch: # UI Trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SELLBRITE_API_KEY: ${{ secrets.SELLBRITE_API_KEY }}
          SELLBRITE_API_SECRET: ${{ secrets.SELLBRITE_API_SECRET }}
        run: node scripts/sync-sellbrite.mjs
