name: Manual Inventory Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Sellbrite sync script
        run: node scripts/sync-sellbrite.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SELLBRITE_API_KEY: ${{ secrets.SELLBRITE_API_KEY }}
          SELLBRITE_API_SECRET: ${{ secrets.SELLBRITE_API_SECRET }}
