name: Sync Sellbrite Inventory

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 9PM CST (3AM UTC)

jobs:
  sync-inventory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Sellbrite inventory sync
        env:
          SELLBRITE_API_KEY: ${{ secrets.SELLBRITE_API_KEY }}
          SELLBRITE_API_SECRET: ${{ secrets.SELLBRITE_API_SECRET }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: node scripts/sync-sellbrite.js

      - name: Run image sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SELLBRITE_API_KEY: ${{ secrets.SELLBRITE_API_KEY }}
          SELLBRITE_API_SECRET: ${{ secrets.SELLBRITE_API_SECRET }}
        run: node scripts/sync-sellbrite-images.mjs

      - name: Merge staging into items
        env:
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: node scripts/merge-staging-to-items.js
