name: Manual Image Sync from Sellbrite

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Manual Inventory Sync"]
    types: [completed]

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🖼 Sync Sellbrite Images → Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SELLBRITE_API_KEY: ${{ secrets.SELLBRITE_API_KEY }}
          SELLBRITE_API_SECRET: ${{ secrets.SELLBRITE_API_SECRET }}
        run: node scripts/sync-sellbrite-images.mjs
